### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by darkoje** [cmsato09/DQMonstersDB-streamlit#16]
https://dqmonstersdb.streamlit.app/

I get "Error running app. If this keeps happening, please [contact support](https://github.com/cmsato09/dqmonstersdb-streamlit/issues/new)."

**Comment by cmsato09** [comment]
@darkoje 
Apologies for the delay. You should be able to access the streamlit app.

Deta recently upgraded from deta.sh to deta.space and I finally migrated the backend FastAPI to their new service. 

https://deta.space/blog/introducing-space

Thanks for trying out the app!
